# Generated by Django 4.0 on 2022-01-10 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('crypto_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=20)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('holding_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.FloatField()),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.crypto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('value', models.FloatField()),
                ('name', models.CharField(blank=True, default='Portfolio_<django.db.models.fields.AutoField>', max_length=255, null=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.crypto')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.holding')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
    ]
