# Generated by Django 4.0 on 2022-01-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='crypto',
        ),
        migrations.AddField(
            model_name='crypto',
            name='portfolio',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.portfolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
