# Generated by Django 4.0 on 2022-01-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_portfolio_crypto_crypto_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='crypto',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.crypto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
