# Generated by Django 4.0 on 2022-01-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_portfolio_crypto_remove_portfolio_holding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='quantity',
        ),
    ]
