# Generated by Django 3.1.6 on 2022-01-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='quantity',
        ),
    ]
