# Generated by Django 3.1.6 on 2022-01-22 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='last_update',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
