# Generated by Django 4.0 on 2022-01-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='type',
            field=models.CharField(blank=True, choices=[('crypto', 'Crypto')], max_length=25),
        ),
    ]
