# Generated by Django 4.0 on 2022-01-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_portfolio_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.account'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='type',
            field=models.CharField(blank=True, choices=[('crypto', 'Crypto')], max_length=25, unique=True),
        ),
    ]
