# Generated by Django 3.1.6 on 2022-01-24 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20220122_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 24, 15, 22, 55, 349674)),
        ),
        migrations.AlterField(
            model_name='holding',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 24, 15, 22, 55, 349802)),
        ),
    ]
