# Generated by Django 3.1.6 on 2022-01-24 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20220124_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.FloatField(verbose_name='Current price'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 24, 15, 43, 23, 634817)),
        ),
        migrations.AlterField(
            model_name='holding',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 24, 15, 43, 23, 634852)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity'),
        ),
    ]
