# Generated by Django 3.1.6 on 2022-02-01 12:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0016_auto_20220201_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holding',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 1, 12, 23, 29, 745003)),
        ),
        migrations.AlterField(
            model_name='holding',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 1, 12, 23, 29, 745114)),
        ),
        migrations.AddField(
            model_name='holding',
            name='type',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.type'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.type'),
        ),
    ]
