# Generated by Django 3.1.6 on 2022-02-04 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20220201_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='holding',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 4, 20, 16, 46, 829789)),
        ),
        migrations.AlterField(
            model_name='holding',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 4, 20, 16, 46, 829807)),
        ),
    ]
