# Generated by Django 3.1.6 on 2022-02-13 07:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20220204_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 13, 7, 23, 24, 789077)),
        ),
        migrations.AlterField(
            model_name='holding',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.type'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 13, 7, 23, 24, 789107)),
        ),
    ]
