# Generated by Django 3.1.6 on 2022-02-13 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20220213_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='price',
        ),
        migrations.AlterField(
            model_name='holding',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 13, 9, 37, 0, 944071)),
        ),
        migrations.AlterField(
            model_name='holding',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 13, 9, 37, 0, 944106)),
        ),
    ]
